version: '3'
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"  # HTTP API and monitoring
      - "6334:6334"  # gRPC API
      - "6335:6335"  # Distributed deployment
    volumes:
      - qdrant_data:/var/lib/qdrant/data
    environment:
      - QDRANT_LOG_LEVEL=info
      - QDRANT_STORAGE_PATH=/var/lib/qdrant/data

volumes:
  qdrant_data:
